Repository Twinsteak/lockerweb, pull requests merged in 2023-09, with the labels that each got.

#330 [chore] pnpm lockfile 버전 업데이트
  pnpm-lock.yaml
Labels: devops

#336 [docs] README url 업데이트
  README.md
Labels: documentation

#338 [fix] jwt 업데이트 대응
  packages/server/src/auth/handler/ssu_login.ts
  packages/server/src/common.ts
  packages/server/src/util/access.ts
  packages/server/template.yaml
Labels: bug, server, auth

#337 [fix] OpenAPI 문서 생성 워크플로우
  .github/workflows/openapi-gen.yml
Labels: bug, documentation

#341 [feat] CloudFront invalidation 스크립트
  package.json
  scripts/cf-invalidate.js
Labels: enhancement, devops

#340 [fix] README의 Deploy 배지
  README.md
Labels: bug, documentation

#333 [feat] SSUToday 로그인 지원
  packages/client/src/lib/api/auth.ts
  packages/client/src/routes/callback/+page.svelte
  packages/server/api.yaml
  packages/server/src/auth/handler/login.ts
  packages/server/src/auth/handler/ssu_login.ts
  packages/server/src/common.ts
  packages/server/src/handler.ts
  packages/server/template.yaml
Labels: server, breaking, client, auth

#342 fix: AWS 배포 Workflow update
  .github/workflows/aws-deploy.yml
Labels: bug

#343 [fix] 클라이언트 배포 시 base url 값을 변경
  packages/client/package.json
Labels: bug, client

#345 [refactor] `aws-sdk` v3로 마이그레이션
  packages/server/dependencies/package.json
  packages/server/package.json
  packages/server/src/auth/data.ts
  packages/server/src/config/data.ts
  packages/server/src/locker/data.ts
  packages/server/src/user/data.ts
  packages/server/src/util/database.ts
  pnpm-lock.yaml
Labels: refactoring, server
